export default {
  login: "Christima-Mary-S",
  id: 69028593,
  node_id: "MDQ6VXNlcjY5MDI4NTkz",
  avatar_url: "https://avatars.githubusercontent.com/u/69028593?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Christima-Mary-S",
  html_url: "https://github.com/Christima-Mary-S",
  followers_url: "https://api.github.com/users/Christima-Mary-S/followers",
  following_url:
    "https://api.github.com/users/Christima-Mary-S/following{/other_user}",
  gists_url: "https://api.github.com/users/Christima-Mary-S/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/Christima-Mary-S/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/Christima-Mary-S/subscriptions",
  organizations_url: "https://api.github.com/users/Christima-Mary-S/orgs",
  repos_url: "https://api.github.com/users/Christima-Mary-S/repos",
  events_url: "https://api.github.com/users/Christima-Mary-S/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/Christima-Mary-S/received_events",
  type: "User",
  site_admin: false,
  name: "Christima Mary S",
  company: "Cochin University of Science And Technology",
  blog: "https://www.linkedin.com/in/christima-mary-s/",
  location: "Kochi",
  email: null,
  hireable: null,
  bio: "Student",
  twitter_username: "iamchristima",
  public_repos: 6,
  public_gists: 0,
  followers: 7,
  following: 8,
  created_at: "2020-07-31T05:20:38Z",
  updated_at: "2022-02-23T16:27:43Z",
};
